// <auto-generated />
using Chess.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chess.API.Migrations
{
    [DbContext(typeof(BoardContext))]
    [Migration("20251002150402_Add_PastBoards")]
    partial class Add_PastBoards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Chess.API.Models.BoardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReversibleMoveNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Turn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BoardEntries");
                });

            modelBuilder.Entity("Chess.API.Models.HistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapturedPiece")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndPosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryEntryNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Piece")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromoteToPiece")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpecialPlyAction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartPosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardEntryId");

                    b.ToTable("HistoryEntry");
                });

            modelBuilder.Entity("Chess.API.Models.SquareEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SquareContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquarePosition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BoardEntryId");

                    b.ToTable("SquareEntry");
                });

            modelBuilder.Entity("Chess.Core.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PastBoards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReversibleMoveNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Squares")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Turn")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Chess.API.Models.HistoryEntry", b =>
                {
                    b.HasOne("Chess.API.Models.BoardEntry", "BoardEntry")
                        .WithMany("History")
                        .HasForeignKey("BoardEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardEntry");
                });

            modelBuilder.Entity("Chess.API.Models.SquareEntry", b =>
                {
                    b.HasOne("Chess.API.Models.BoardEntry", "BoardEntry")
                        .WithMany("Squares")
                        .HasForeignKey("BoardEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoardEntry");
                });

            modelBuilder.Entity("Chess.API.Models.BoardEntry", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Squares");
                });
#pragma warning restore 612, 618
        }
    }
}
