// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Chess.API.Migrations
{
    /// <inheritdoc />
    public partial class Add_New_Unused_Models : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "Turn",
                table: "Boards",
                type: "INTEGER",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "INTEGER");

            migrationBuilder.CreateTable(
                name: "BoardEntries",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    Rows = table.Column<int>(type: "INTEGER", nullable: false),
                    Columns = table.Column<int>(type: "INTEGER", nullable: false),
                    Turn = table.Column<int>(type: "INTEGER", nullable: true),
                    ReversibleMoveNumber = table.Column<int>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BoardEntries", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "HistoryEntry",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    BoardEntryId = table.Column<int>(type: "INTEGER", nullable: false),
                    HistoryEntryNumber = table.Column<int>(type: "INTEGER", nullable: false),
                    Piece = table.Column<string>(type: "TEXT", nullable: false),
                    StartPosition = table.Column<string>(type: "TEXT", nullable: false),
                    EndPosition = table.Column<string>(type: "TEXT", nullable: false),
                    CapturedPiece = table.Column<string>(type: "TEXT", nullable: true),
                    SpecialPlyAction = table.Column<int>(type: "INTEGER", nullable: true),
                    PromoteToPiece = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HistoryEntry", x => x.Id);
                    table.ForeignKey(
                        name: "FK_HistoryEntry_BoardEntries_BoardEntryId",
                        column: x => x.BoardEntryId,
                        principalTable: "BoardEntries",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "SquareEntry",
                columns: table => new
                {
                    Id = table.Column<int>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    BoardEntryId = table.Column<int>(type: "INTEGER", nullable: false),
                    SquarePosition = table.Column<string>(type: "TEXT", nullable: false),
                    SquareContent = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SquareEntry", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SquareEntry_BoardEntries_BoardEntryId",
                        column: x => x.BoardEntryId,
                        principalTable: "BoardEntries",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_HistoryEntry_BoardEntryId",
                table: "HistoryEntry",
                column: "BoardEntryId");

            migrationBuilder.CreateIndex(
                name: "IX_SquareEntry_BoardEntryId",
                table: "SquareEntry",
                column: "BoardEntryId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "HistoryEntry");

            migrationBuilder.DropTable(
                name: "SquareEntry");

            migrationBuilder.DropTable(
                name: "BoardEntries");

            migrationBuilder.AlterColumn<int>(
                name: "Turn",
                table: "Boards",
                type: "INTEGER",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "INTEGER",
                oldNullable: true);
        }
    }
}
