// <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Chess.API.Migrations
{
    /// <inheritdoc />
    public partial class RenameofColumn : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "NumberOfPlysSinceCaptureOrPawnMove",
                table: "Boards",
                newName: "ReversibleMoveNumber");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "ReversibleMoveNumber",
                table: "Boards",
                newName: "NumberOfPlysSinceCaptureOrPawnMove");
        }
    }
}
